#!/bin/bash

## Repository Management

git init - Create a new Git Repo in current folder

git clone <url> - Copy(clone) a remote repo locally

git remote -v - Show Linked Remotes

git remote add origin <url> - Add remote repo link

git remote remove origin - Remove linked remote


## Staging and Committing

git status - Check which files are staged unstaged

git add <file> - Stage a specific file

git add . - Stage all modified files

git commit -m "msg" - Commit staged changes with message

git commit -am "msg" - Add + commit tracked files in one step

git rm <file> - Remove a file from working dir + stage

git mv old new - Rename file in Git

git rm --cache <file> - To unstaged the staged file and stop tracking file

git restore --staged <file> - Unstages the file (moves it from staging area back to working directory), do not affect tracking, keeps the file exactly as it is


## View Changes and Logs

git log - Show commit history

git log --oneline - Compact log view

git diff - Show unstaged changes

git diff --staged - Show staged changes

git show <commit> - Show full details of a commit

git blame <file> - See who last modified each line

## Branching

git branch - List all local branches

git branch <name> - Create a new branch

git checkout <branch> - Switch to a branch

git checkout -b <name> - Create and switch to new branch

git merge <branch> - Merge a branch into current branch

git branch -d <name> - Delete a local branch

git rebase <branch> - Reapply commits from the head to the tip of branch
